### get a token
POST https://accounts.spotify.com/api/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=6428b163585e4c2295c4232278eac6f7&client_secret=5289a351467b45d2b65130ad2e640f61
    
### get an artist
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg
Authorization: Bearer BQDYNUEWSgT2OeS4t3XBBd96SYLLCSpGN_HXNMcJg012JwQ9KcyZ79ADrIxxjgRNNq_gK1yH_9IOHWGOIpKEm5iKzy9UI4dug3VinGBZNA1XR5zhO8Ch

### get artist top tracks
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/top-tracks?market=us
Authorization: Bearer BQDYNUEWSgT2OeS4t3XBBd96SYLLCSpGN_HXNMcJg012JwQ9KcyZ79ADrIxxjgRNNq_gK1yH_9IOHWGOIpKEm5iKzy9UI4dug3VinGBZNA1XR5zhO8Ch

###get artist albums
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/albums?include_groups=album%2Csingle&market=us
Authorization: Bearer BQDYNUEWSgT2OeS4t3XBBd96SYLLCSpGN_HXNMcJg012JwQ9KcyZ79ADrIxxjgRNNq_gK1yH_9IOHWGOIpKEm5iKzy9UI4dug3VinGBZNA1XR5zhO8Ch


### get related artist 
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/related-artist
Authorization: Bearer BQDYNUEWSgT2OeS4t3XBBd96SYLLCSpGN_HXNMcJg012JwQ9KcyZ79ADrIxxjgRNNq_gK1yH_9IOHWGOIpKEm5iKzy9UI4dug3VinGBZNA1XR5zhO8Ch

### get featured on 
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/albums?include_groups=appears_on&market=us
Authorization: Bearer BQDYNUEWSgT2OeS4t3XBBd96SYLLCSpGN_HXNMcJg012JwQ9KcyZ79ADrIxxjgRNNq_gK1yH_9IOHWGOIpKEm5iKzy9UI4dug3VinGBZNA1XR5zhO8Ch

### test route for server
GET http://localhost:8080/