### get a token
POST https://accounts.spotify.com/api/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=6428b163585e4c2295c4232278eac6f7&client_secret=5289a351467b45d2b65130ad2e640f61
    
### get an artist
GET https://api.spotify.com/v1/artists/3fMbdgg4jU18AjLCKBhRSm
Authorization: Bearer BQCgbo7WqMfr2EUigTlecWLgnXB9WLw5BW9x8GaOJPPo31TNq7GILNumxT3SkcqP-cpht5XP4F02eZv_cFqUVzd73TvZHpBVX-_TWyKqKlT4LHlC1o9G
### get artist top tracks
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/top-tracks?market=us
Authorization: Bearer BQA3WGQWli-yg4gqLYf4D4fX7wTTt7fGCLeNwvDp7JrB2BfC4c8MGRIdYEowJCzaGBqOAbaTpYxEERiSXWJKOhz1KwC0Ln1JBoTAugRt_z6aWyXdRXhQ

###get artist albums
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/albums?include_groups=album%2Csingle&market=us
Authorization: Bearer BQA3WGQWli-yg4gqLYf4D4fX7wTTt7fGCLeNwvDp7JrB2BfC4c8MGRIdYEowJCzaGBqOAbaTpYxEERiSXWJKOhz1KwC0Ln1JBoTAugRt_z6aWyXdRXhQ

### get related artist 
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/related-artist
Bearer BQCJeuhy8ByVhsHgAtDubAloMgCRQ_d2A9q5ZD0Txx0-668SpwPI_82lD0AjO4KSOfaYhoptbP3AgEXnyTQbS5OPZjYTUUQ8Rsfxp6zA5syKsUEhO_0n

###get featured on 
GET https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg/albums?include_groups=appears_on&market=us
Authorization: Bearer BQCJeuhy8ByVhsHgAtDubAloMgCRQ_d2A9q5ZD0Txx0-668SpwPI_82lD0AjO4KSOfaYhoptbP3AgEXnyTQbS5OPZjYTUUQ8Rsfxp6zA5syKsUEhO_0n

### test route for server
GET http://localhost:4000/


### get album
GET https://api.spotify.com/v1/albums/4RaAjieYFIZRF8uh6GY43r?market=us
Authorization: Bearer BQDVI0-asnGciPNdme6763JAxyQIinryEaADr172BPonu3sXMoLlBgwo-Y7-DDMdSFcVodk7ZGubo1TRQ7NvCTIN6S0toI5FWSZulKSyvWcp2ROUkvxS

### get track
GET https://api.spotify.com/v1/tracks/7lVHsLX1Tgy0UqQFk8NsCO?market=us
Authorization: Bearer BQCgbo7WqMfr2EUigTlecWLgnXB9WLw5BW9x8GaOJPPo31TNq7GILNumxT3SkcqP-cpht5XP4F02eZv_cFqUVzd73TvZHpBVX-_TWyKqKlT4LHlC1o9G